version: '3.1'

services:
  wp:
    image: wordpress:latest
    restart: always
    ports:
      - 1100:80
    env_file: .env
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
